apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - account.yaml
  - build-push-ma-base-image.yaml
  - publish.yaml
  - release-pipeline-nightly.yaml
  - release-pipeline.yaml
  - resources.yaml
